name: Build Windows Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: ${{ matrix.architecture }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-win.txt
        pip install pyinstaller
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --add-data "README.md;." --onefile --name "QR2Key-${{ matrix.architecture }}" --target-architecture ${{ matrix.architecture }} qr2key/main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QR2Key-${{ matrix.architecture }}
        path: dist/QR2Key-${{ matrix.architecture }}.exe
